
server:
  port: 1111
eureka:
  instance:
    hostname: peer1
    instance-id: # 表示制定实例名
  client:
#    register-with-eureka: false  表示注册到服务中心
#    fetch-registry: false
    serviceUrl:
      defaultZone: http://peer2:1112/eureka/
  server:
    # 关闭server的自我保护机制
    # 自我保护机制：server会统计心跳失败的比例在15钟之内是否低于15%，如果低于，server就会将实例保护，并不让其过期
    #             在保护期内出现问题，会使得客户端调用失败。关闭后确保将其正确剔除
    enable-self-preservation: false
