spring:
  cloud:
    config:
      server:
        git:
          # ?????????git???
          uri:
          # ?????????????¦Ë??
          search-paths:
          # ?????
          username:
          # ????
          password:
# ???http??postman????????????lable-?????????
#  /{application}/{profile}[/{lable}]
#  /{application}-{profile}.properties/yml
#  /{lable}/{application}-{profile}.properties/yml
